### ISSUE TITLE
MAME Compatibility Please

### ISSUE THREAD

**Issue by fraser125** [tj90241/n64chain#3]
The following line fails on MAME because they have not implemented any behavior involving bit 0x08 in the PI Status Register. 

https://github.com/tj90241/n64chain/blob/1454d1789c4b9bb444c51ff5b28df4e7d8cdec7e/libn64/os/asm/boot.s#L102

By commenting this line I was able to successfully run libn64 generated roms. Commenting this line changes the condition to wait until the PI status register is zero. It may not perform as well but it works safely. 

Please consider a compatible change. Thanks.

**Comment by tj90241** [comment]
I'd rather not patch things up so emulators work (rather, the emulators should patch in the missing functionality). It's a slippery slope...

**However**, in this case, I don't think I'm using the bit specified by the mask (0x8) correctly in this case anyways, so this should probably be patched.

**Comment by tj90241** [comment]
So, I think it actually was working correctly before on real HW. There's an undocumented bit (3rd from LSB) that goes high alongside a PI interrupt. I was formerly spinning on that bit, but changed it to spin on the PI DMA busy bit instead: 05b728e35ac5076dbb3b3d292d69d3af7d3d3494
