### ISSUE TITLE
Readme for build dependencies

### ISSUE THREAD

**Issue by networkfusion** [tj90241/n64chain#4]
Please can a readme for the build dependencies be stated (e.g. apt-get install...) as currently the build fails on a clean ubuntu machine (win64 but possibly Linux also). I am attempting to make a travis CI script to automate the builds so that there is a common download location for Altra64 (and others) https://github.com/n64-tools

the actual error I am getting is "error: C compiler cannot create executables"

**Comment by ijacquez** [comment]
Can you post snippets of the log?

**Comment by networkfusion** [comment]
![image](https://user-images.githubusercontent.com/11439699/37233789-8cbd8022-23ec-11e8-8df3-cf028735c6e2.png)

I have just added sudo apt install -y libc6-dev to the build script... I will see if it makes a difference...
You can see the progress of travis ci by clicking on any of the build attempts at https://github.com/N64-tools/mips64-gcc-toolchain/commits/master

**Comment by ijacquez** [comment]
There's another log within the build files. I think it's  ´config.log´.

**Comment by networkfusion** [comment]
it is travis-ci, so I am not sure I have access to it... I will post updates when I make more progress...

**Comment by networkfusion** [comment]
I have a feeling that the problem is it is going to the dir '/binutils-build/intl' rather than '/binutils-build/'... however I am now struggling to see my screen (tiredness and beer) so I give up for now!

**Comment by tj90241** [comment]
The Debian requirements should be:
```
build-essential
libgmp-dev
libmpfr-dev
libmpc-dev
```

Can you please ensure you have these packages installed and try again?

**Comment by networkfusion** [comment]
I am getting further than before (the main problem was it wont build on Ubuntu 14.04) but with Ubuntu 16.04 I am still getting the following error (I am running the Linux script and then the windows script): 
![image](https://user-images.githubusercontent.com/11439699/37304487-9c133fa0-2629-11e8-9069-be6e0d99c66d.png)

**Comment by ijacquez** [comment]
I believe that you need to set the **PATH** variable to the installation path before you start building

**Comment by networkfusion** [comment]
the Path var is set at the start of both of the scripts already...
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${SCRIPT_DIR} && mkdir -p {stamps,tarballs}

export PATH="${PATH}:${SCRIPT_DIR}/bin"
```

**Comment by networkfusion** [comment]
why is there and `exit 0` on line 70 of `build-linux64-toolchain.sh`? that would explain why GCC is not created for Linux, and why windows fails...

**Comment by tj90241** [comment]
The randomly placed exit was a bug and a fix has already been committed to master.

Israel is correct in that if you're (cross) building the Windows toolchain, mips64-gcc-linux (preferably built by the Linux toolchain) must be in your path. If you're building the Linux toolchain only, you shouldn't get that error.

**Comment by networkfusion** [comment]
I have now got it to successfully build on Ubuntu 16.04 using travis ci (see https://github.com/N64-tools/mips64-gcc-toolchain for what is required)... I will continue to improve it (bash is not one of my strengths) and might even push to a launchpad PPA and create a windows installer, but would have the following suggestions for you if you are at all interested:

- Use https download links rather than ftp as it can fail if too many people are connected at the same time (gnu are closing the ftp capability at some point anyway)
- Have a master script that you can choose whether you are building for Linux or all (Linux and Windows) creating appropriate dirs for each with global exports.
- Split out the n64chain related stuff so you can just build the GCC toolchain and add n64chain stuff if you wish...
- Have a version (possibly use the GCC version and secondary n64chain version (e.g. 7.3.0-1.0) like they do for the ARM toolchain
- Also use a CI-CD pipeline (it makes life easier in the long run imho)

Also, if you are interested, I created a GitHub organization called N64-Tools and I can add you to it if you wish. I wanted to group all of the N64 dev tools in a single place, mainly so they didn't clutter my personal repos but also so they are easier to find for others...
