### ISSUE TITLE
header.bin missing from libn64 directory

### ISSUE THREAD

**Issue by bxlentpartyon** [tj90241/n64chain#5]
I'm trying to build the sample code in the helloworld directory, but I'm getting this error:

```make
athorlton@linux-46if:~/hacks/n64/git/n64chain/helloworld> make
Building: helloworld/helloworld.elf
Building: helloworld/helloworld.z64
fopen: No such file or directory
Makefile:68: recipe for target 'helloworld.z64' failed
make: *** [helloworld.z64] Error 1
```

It looks like the error is coming from `checksum`:

```
Makefile:
 67 $(ROM_NAME).z64: $(ROM_NAME).elf
 68         @echo $(call FIXPATH,"Building: $(ROM_NAME)/$@")
 69         @$(OBJCOPY) -O binary $< $@
 70         @$(CHECKSUM) $(call FIXPATH,../libn64/header.bin) $@
```
```
checksum.c:
127   // Open header, read it into memory, close.
128   if ((buffer = calloc(min_sz, 1)) == NULL) {
129     perror("calloc");
130 
131     return EXIT_FAILURE;
132   }
133 
134   if ((f = fopen(argv[1], "rb")) == NULL) {
135     perror("fopen");
136     free(buffer);
137 
138     return EXIT_FAILURE;
139   }

```
From what I can tell, it's because the `header.bin` file isn't in `libn64`.  I poked around, and didn't see a file like that anywhere, and don't see any code that looks like it's supposed to construct it.

Am I missing something or has that file just been left out?

**Comment by bxlentpartyon** [comment]
FWIW, I was able to build and successfully run the resulting ROM, using the header that ships with libdragon.

**Comment by tj90241** [comment]
I purposely didn't put it in there because I'm fairly certain it's copyright-ed IPL code.

**Comment by bxlentpartyon** [comment]
Ahh, got it.  I wondered if it might be - just wanted to check.  Thanks for letting me know!

**Comment by gameblabla** [comment]
There's a custom bootcode that doesn't seem to use Nintendo's code :
https://github.com/pseudophpt/pseultra
https://github.com/pseudophpt/pseultra/blob/master/n64/boot/src/boot.sx

Perhaps it could be used instead ? I couldn't manage to make it work due to the checksum issues though.
https://github.com/pseudophpt/pseultra/wiki/Tool:-boot
https://github.com/pseudophpt/pseultra/wiki/Tool:-bootcsum

**Comment by hcs64** [comment]
Oh wow, someone finally made a hash collider for IPL, thanks for the link!
